In [1]:
import pandas as pd
import numpy as np

In [3]:
pla=pd.read_csv("DataSets/Placement_Data.csv")
pla.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [4]:
pla.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [5]:
pla["salary"].fillna(value=np.mean(pla['salary']),inplace=True)

In [6]:
pla.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status         salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.000000  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.000000  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.000000  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed  288655.405405  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.000000

In [7]:
car.isnull().sum()

Manufacturer            0
Model                   0
Sales in thousands      0
x_4_year               36
Vehicle type            0
Price in thousands      2
Engine size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb weight             2
Fuel capacity           1
Fuel efficiency         3
Latest Launch           0
Unnamed: 15           157
XX                     36
dtype: int64

In [8]:
car["x_4_year"].fillna(value=np.mean(car["x_4_year"]),inplace=True)

In [9]:
car["Price in thousands"].fillna(value=np.mean(car["Price in thousands"]),inplace=True)

In [10]:
car["Length"].fillna(value=np.mean(car["Length"]),inplace=True)

In [11]:
car["Width"].fillna(value=np.mean(car["Width"]),inplace=True)

In [12]:
car["Curb weight"].fillna(value=np.mean(car["Curb weight"]),inplace=True)

In [13]:
car["Fuel capacity"].fillna(value=np.mean(car["Fuel capacity"]),inplace=True)

In [14]:
car["Horsepower"].fillna(value=np.mean(car["Horsepower"]),inplace=True)

In [15]:
car["Engine size"].fillna(value=np.mean(car['Engine size']),inplace=True)

In [16]:
car["Wheelbase"].fillna(value=np.mean(car["Wheelbase"]),inplace=True)

In [17]:
car['Fuel efficiency'].fillna(value=np.mean(car['Fuel efficiency']),inplace=True)

In [18]:
car.isnull().sum()

Manufacturer            0
Model                   0
Sales in thousands      0
x_4_year                0
Vehicle type            0
Price in thousands      0
Engine size             0
Horsepower              0
Wheelbase               0
Width                   0
Length                  0
Curb weight             0
Fuel capacity           0
Fuel efficiency         0
Latest Launch           0
Unnamed: 15           157
XX                     36
dtype: int64

In [19]:
car.drop("Unnamed: 15",axis=1,inplace=True)

In [20]:
car.drop("XX",axis=1,inplace=True)

In [21]:
car.head(20)

Manufacturer              Model  Sales in thousands   x_4_year  \
0   Acura          Integra                        16.919  16.360000   
1   Acura          TL                             39.384  19.875000   
2   Acura          CL                             14.114  18.225000   
3   Acura          RL                              8.588  29.725000   
4   Audi           A4                             20.397  22.255000   
5   Audi           A6                             18.780  23.555000   
6   Audi           A8                              1.380  39.000000   
7   BMW            323i                           19.747  18.072975   
8   BMW            328i                            9.231  28.675000   
9   BMW            528i                           17.527  36.125000   
10  Buick          Century                        91.561  12.475000   
11  Buick          Regal                          39.350  13.740000   
12  Buick          Park Avenue                    27.851  20.190000   
13  Buick          LeSabre                        83.257  13.360000   
14  Cadillac       DeVille                        63.729  22.525000   
15  Cadillac       Seville                        15.943  27.100000   
16  Cadillac       Eldorado                        6.536  25.725000   
17  Cadillac       Catera                         11.185  18.225000   
18  Cadillac       Escalade                       14.785  18.072975   
19  Chevrolet      Cavalier                      145.519   9.250000   

   Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  \
0     Passenger           21.500000          1.8       140.0      101.2   
1     Passenger           28.400000          3.2       225.0      108.1   
2     Passenger           27.390755          3.2       225.0      106.9   
3     Passenger           42.000000          3.5       210.0      114.6   
4     Passenger           23.990000          1.8       150.0      102.6   
5     Passenger           33.950000          2.8       200.0      108.7   
6     Passenger           62.000000          4.2       310.0      113.0   
7     Passenger           26.990000          2.5       170.0      107.3   
8     Passenger           33.400000          2.8       193.0      107.3   
9     Passenger           38.900000          2.8       193.0      111.4   
10    Passenger           21.975000          3.1       175.0      109.0   
11    Passenger           25.300000          3.8       240.0      109.0   
12    Passenger           31.965000          3.8       205.0      113.8   
13    Passenger           27.885000          3.8       205.0      112.2   
14    Passenger           39.895000          4.6       275.0      115.3   
15    Passenger           44.475000          4.6       275.0      112.2   
16    Passenger           39.665000          4.6       275.0      108.0   
17    Passenger           31.010000          3.0       200.0      107.4   
18          Car           46.225000          5.7       255.0      117.5   
19    Passenger           13.260000          2.2       115.0      104.1   

    Width  Length  Curb weight  Fuel capacity  Fuel efficiency Latest Launch  
0    67.3   172.4     2.639000           13.2             28.0      2-Feb-14  
1    70.3   192.9     3.517000           17.2             25.0      6-Mar-15  
2    70.6   192.0     3.470000           17.2             26.0      1-Apr-14  
3    71.4   196.6     3.850000           18.0             22.0      3-Oct-15  
4    68.2   178.0     2.998000           16.4             27.0     10-Aug-15  
5    76.1   192.0     3.561000           18.5             22.0      8-Sep-15  
6    74.0   198.2     3.902000           23.7             21.0     27-Feb-14  
7    68.4   176.0     3.179000           16.6             26.0     28-Jun-15  
8    68.5   176.0     3.197000           16.6             24.0     29-Jan-14  
9    70.9   188.0     3.472000           18.5             25.0      4-Apr-15  
10   72.7   194.6     3.368000           17.5             25.0     1

In [22]:
car.columns

Index(['Manufacturer', 'Model', 'Sales in thousands', 'x_4_year',
       'Vehicle type', 'Price in thousands', 'Engine size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb weight', 'Fuel capacity',
       'Fuel efficiency', 'Latest Launch'],
      dtype='object')

In [23]:
car.index

RangeIndex(start=0, stop=157, step=1)

In [24]:
pla.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [25]:
pla.index

RangeIndex(start=0, stop=215, step=1)

# 7

In [26]:
#7.1
bmin=car['Sales in thousands'].min()
car.loc[car['Sales in thousands']==bmin,['Manufacturer','Model']]

Manufacturer              Model
83  Mitsubishi     3000GT

In [27]:
#7.2
bmin=car['Sales in thousands'].max()
car.loc[car['Sales in thousands']==bmin,['Manufacturer','Model']]

Manufacturer              Model
56  Ford           F-Series

In [74]:
#7.3
a=car.loc[car['Vehicle type']=='Passenger','Sales in thousands']
car.loc[car['Sales in thousands']==a.min(),['Manufacturer','Model']]

Manufacturer              Model
83  Mitsubishi     3000GT

In [29]:
#7.4
a=car.loc[car['Engine size']>6,'Sales in thousands']
car.loc[car['Sales in thousands']==a.max(),['Manufacturer','Model']]

Manufacturer              Model
39  Dodge          Viper

In [30]:
#7.5
a=car.loc[car['Vehicle type']=='Car','Fuel efficiency']
b=a.max()
car.loc[car['Fuel efficiency']==b,'Manufacturer']

4      Audi         
19     Chevrolet    
22     Chevrolet    
27     Chevrolet    
31     Chrysler     
58     Honda        
63     Hyundai      
97     Mercedes-Benz
110    Oldsmobile   
115    Plymouth     
118    Pontiac      
132    Saturn       
137    Toyota       
142    Toyota       
147    Volkswagen   
Name: Manufacturer, dtype: object

In [31]:
#7.6
a=car.loc[car['Vehicle type']=='Passenger','Fuel efficiency']
b=a.min()
car.loc[car['Fuel efficiency']==b,'Manufacturer']

39    Dodge        
42    Dodge        
54    Ford         
Name: Manufacturer, dtype: object

In [32]:
#7.7
l=car['Price in thousands'].min()
s=car['Sales in thousands'].max()
car.loc[(car['Price in thousands']==l)|(car['Sales in thousands']==s),"Manufacturer"]

26    Chevrolet    
56    Ford         
Name: Manufacturer, dtype: object

In [33]:
#7.8
l=car['Price in thousands'].max()
s=car['Sales in thousands'].min()
car.loc[(car['Price in thousands']==l)|(car['Sales in thousands']==s),"Manufacturer"]

83    Mitsubishi   
99    Mercedes-Benz
Name: Manufacturer, dtype: object

In [34]:
#7.9
a=car['Horsepower'].max()
car.loc[car['Horsepower']==a,'Model']

39    Viper            
Name: Model, dtype: object

In [35]:
#7.10
mx=car['Fuel efficiency'].max()
mi=car['Sales in thousands'].min()
car.loc[(car['Fuel efficiency']==mx)|(car['Sales in thousands']==mi),['Model','Manufacturer']] 

Model   Manufacturer
26  Metro              Chevrolet    
83  3000GT             Mitsubishi

In [36]:
#7.11
mi=car['Fuel efficiency'].min()
mx=car['Sales in thousands'].max()
car.loc[(car['Fuel efficiency']==mi)|(car['Sales in thousands']==mx),['Model','Manufacturer']] 

Model   Manufacturer
18   Escalade           Cadillac     
41   Ram Wagon          Dodge        
56   F-Series           Ford         
74   LX470              Lexus        
78   Navigator          Lincoln      
144  Land Cruiser       Toyota

In [37]:
#7.12
a=car.loc[car['Vehicle type']=='Car','Wheelbase']
car.loc[car['Wheelbase']==a.max(),['Manufacturer','Model']]

Manufacturer              Model
40  Dodge          Ram Pickup

In [38]:
#7.13
a=car.loc[car['Vehicle type']=='passenger','Wheelbase']
car.loc[car['Wheelbase']==a.min(),['Manufacturer','Model']]

Empty DataFrame
Columns: [Manufacturer, Model]
Index: []

In [39]:
#7.14
m=car['Curb weight'].max()
n=car['Fuel efficiency'].max()
car.loc[(car['Curb weight']==m)|(car['Fuel efficiency']==n),['Model','Manufacturer']] 

Model   Manufacturer
18  Escalade           Cadillac     
26  Metro              Chevrolet

In [40]:
#7.15
m=car['Curb weight'].min()
n=car['Fuel efficiency'].max()
car.loc[(car['Curb weight']==m)|(car['Fuel efficiency']==n),['Model','Manufacturer']] 

Model   Manufacturer
26  Metro              Chevrolet

In [41]:
#7.16
m=car['Curb weight'].min()
n=car['Fuel efficiency'].min()
car.loc[(car['Curb weight']==m)|(car['Fuel efficiency']==n),['Model','Manufacturer']] 

Model   Manufacturer
18   Escalade           Cadillac     
26   Metro              Chevrolet    
41   Ram Wagon          Dodge        
74   LX470              Lexus        
78   Navigator          Lincoln      
144  Land Cruiser       Toyota

In [42]:
#7.17
car.rename(columns={'x_4_year':'4_Year_Resale_Value'},inplace=True)

In [43]:
car.head(1)

Manufacturer              Model  Sales in thousands  4_Year_Resale_Value  \
0  Acura          Integra                        16.919                16.36   

  Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  Width  \
0    Passenger                21.5          1.8       140.0      101.2   67.3   

   Length  Curb weight  Fuel capacity  Fuel efficiency Latest Launch  
0   172.4        2.639           13.2             28.0      2-Feb-14

In [44]:
#7.18
m=car['Sales in thousands'].max()
n=car['4_Year_Resale_Value'].max()
car.loc[(car['Sales in thousands']==m)|(car['4_Year_Resale_Value']==n),['Model','Manufacturer']] 

Model   Manufacturer
56   F-Series           Ford         
126  Carrera Cabriolet  Porsche

In [45]:
#7.19
m=car['Sales in thousands'].max()
n=car['4_Year_Resale_Value'].max()
l=car['Fuel efficiency'].max()
p=car['Price in thousands'].min()
car.loc[(car['Sales in thousands']==m)|(car['4_Year_Resale_Value']==n)|(car['Fuel efficiency']==l)&(car['Price in thousands']==p),['Model','Manufacturer']] 

Model   Manufacturer
26   Metro              Chevrolet    
56   F-Series           Ford         
126  Carrera Cabriolet  Porsche

In [46]:
#7.20
m=car['Sales in thousands'].max()
n=car['4_Year_Resale_Value'].min()
car.loc[(car['Sales in thousands']==m)&(car['4_Year_Resale_Value']==n),['Model','Manufacturer']] 

Empty DataFrame
Columns: [Model, Manufacturer]
Index: []

In [47]:
#7.21


# 8

In [48]:
#8.1
pla[(pla['gender']=='M')].nlargest(5, ['salary'])


sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
119    120      M  60.80  Central  68.40  Central  Commerce     64.60   
150    151      M  71.00  Central  58.66  Central   Science     58.00   
77      78      M  64.00   Others  80.00   Others   Science     65.00   
163    164      M  63.00   Others  67.00   Others   Science     64.00   
174    175      M  73.24   Others  50.83   Others   Science     64.27   

      degree_t workex  etest_p specialisation  mba_p  status    salary  
119  Comm&Mgmt    Yes    82.66        Mkt&Fin  64.34  Placed  940000.0  
150   Sci&Tech    Yes    56.00        Mkt&Fin  61.30  Placed  690000.0  
77    Sci&Tech    Yes    69.00        Mkt&Fin  57.65  Placed  500000.0  
163   Sci&Tech     No    75.00        Mkt&Fin  66.46  Placed  500000.0  
174   Sci&Tech    Yes    64.00        Mkt&Fin  66.23  Placed  500000.0

In [49]:
#8.2
pla[(pla['gender']=='M')].nsmallest(5, ['salary'])

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
1        2      M  79.33  Central  78.33   Others   Science     77.48   
107    108      M  82.00   Others  90.00   Others  Commerce     83.00   
47      48      M  63.00  Central  60.00  Central  Commerce     57.00   
209    210      M  62.00  Central  72.00  Central  Commerce     65.00   
73      74      M  64.60  Central  83.83   Others  Commerce     71.72   

      degree_t workex  etest_p specialisation  mba_p  status    salary  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28  Placed  200000.0  
107  Comm&Mgmt     No     80.0         Mkt&HR  73.52  Placed  200000.0  
47   Comm&Mgmt    Yes     78.0        Mkt&Fin  54.55  Placed  204000.0  
209  Comm&Mgmt     No     67.0        Mkt&Fin  56.49  Placed  216000.0  
73   Comm&Mgmt     No     86.0        Mkt&Fin  59.75  Placed  218000.0

In [50]:
#8.3
pla[(pla['gender']=='F')].nlargest(15, ['salary'])

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
177    178      F  73.00  Central  97.00   Others  Commerce     79.00   
85      86      F  83.84   Others  89.83   Others  Commerce     77.20   
21      22      F  79.00   Others  76.00   Others  Commerce     85.00   
22      23      F  69.80   Others  60.80   Others   Science     72.23   
131    132      F  74.90   Others  57.00   Others   Science     62.00   
125    126      F  84.00  Central  73.00  Central  Commerce     73.00   
37      38      F  79.00  Central  76.00  Central   Science     65.60   
23      24      F  77.40   Others  60.00   Others   Science     64.74   
35      36      F  69.00  Central  78.00  Central  Commerce     72.00   
90      91      F  85.00   Others  90.00   Others  Commerce     82.00   
96      97      F  76.00  Central  70.00  Central   Science     76.00   
102    103      F  77.00   Others  61.00   Others  Commerce     68.00   
193    194      F  60.00  Central  63.00  Central      Arts     56.00   
6        7      F  46.00   Others  49.20   Others  Commerce     79.00   
12      13      F  47.00  Central  55.00   Others   Science     65.00   

      degree_t workex  etest_p specialisation  mba_p      status  \
177  Comm&Mgmt    Yes    89.00        Mkt&Fin  70.81      Placed   
85   Comm&Mgmt    Yes    78.74        Mkt&Fin  76.18      Placed   
21   Comm&Mgmt     No    95.00        Mkt&Fin  69.06      Placed   
22    Sci&Tech     No    55.53         Mkt&HR  68.81      Placed   
131     Others    Yes    80.00        Mkt&Fin  60.78      Placed   
125  Comm&Mgmt     No    75.00        Mkt&Fin  73.33      Placed   
37    Sci&Tech     No    58.00         Mkt&HR  55.47      Placed   
23    Sci&Tech    Yes    92.00        Mkt&Fin  63.62      Placed   
35   Comm&Mgmt     No    71.00         Mkt&HR  62.74      Placed   
90   Comm&Mgmt     No    92.00        Mkt&Fin  68.03      Placed   
96   Comm&Mgmt    Yes    66.00        Mkt&Fin  64.44      Placed   
102  Comm&Mgmt    Yes    57.50        Mkt&Fin  61.31      Placed   
193     Others    Yes    80.00         Mkt&HR  56.63      Placed   
6    Comm&Mgmt     No    74.28        Mkt&Fin  53.29  Not Placed   
12   Comm&Mgmt     No    62.00         Mkt&HR  65.04  Not Placed   

            salary  
177  650000.000000  
85   400000.000000  
21   393000.000000  
22   360000.000000  
131  360000.000000  
125  350000.000000  
37   320000.000000  
23   300000.000000  
35   300000.000000  
90   300000.000000  
96   300000.000000  
102  300000.000000  
193  300000.000000  
6    288655.405405  
12   288655.405405

In [51]:
#8.4
pla[(pla['gender']=='F')].nsmallest(10, ['salary'])

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
15      16      F   65.0  Central   75.0  Central  Commerce      69.0   
44      45      F   77.0   Others   73.0   Others  Commerce      81.0   
50      51      F   75.2  Central   73.2  Central   Science      68.4   
135    136      F   72.0  Central   56.0   Others   Science      69.0   
213    214      F   74.0   Others   66.0   Others  Commerce      58.0   
88      89      F   66.0  Central   62.0  Central  Commerce      73.0   
89      90      F   84.0   Others   75.0   Others   Science      69.0   
126    127      F   79.0   Others   61.0   Others   Science      75.5   
204    205      F   74.0   Others   73.0   Others  Commerce      73.0   
54      55      F   74.0  Central   60.0   Others   Science      69.0   

      degree_t workex  etest_p specialisation  mba_p  status    salary  
15   Comm&Mgmt    Yes     72.0        Mkt&Fin  64.66  Placed  200000.0  
44   Comm&Mgmt    Yes     89.0        Mkt&Fin  69.70  Placed  200000.0  
50   Comm&Mgmt     No     65.0         Mkt&HR  62.98  Placed  200000.0  
135  Comm&Mgmt     No     55.6         Mkt&HR  65.63  Placed  200000.0  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23  Placed  204000.0  
88   Comm&Mgmt     No     58.0         Mkt&HR  64.36  Placed  210000.0  
89    Sci&Tech    Yes     62.0         Mkt&HR  62.36  Placed  210000.0  
126   Sci&Tech    Yes     70.0        Mkt&Fin  68.20  Placed  210000.0  
204  Comm&Mgmt    Yes     80.0        Mkt&Fin  67.69  Placed  210000.0  
54   Comm&Mgmt     No     78.0         Mkt&HR  65.56  Placed  216000.0

In [24]:
#8.5
a=pla.loc[(pla['hsc_s']=='Commerce')&(pla['gender']=='F'),'salary']
a
pla[pla['salary']==a.max()]

sl_no gender  ssc_p    ssc_b  hsc_p   hsc_b     hsc_s  degree_p  \
177    178      F   73.0  Central   97.0  Others  Commerce      79.0   

      degree_t workex  etest_p specialisation  mba_p  status    salary  
177  Comm&Mgmt    Yes     89.0        Mkt&Fin  70.81  Placed  650000.0

In [26]:
#8.6
# c=pla.loc[(pla['hsc_s']=='Arts')&(pla['gender']=='F'),'salary']
# c
# a=c.max()
# pla[pla['salary']==a]#Don't know why the desired output is not comming
a=pla[(pla['hsc_s']=='Arts')&(pla['gender']=='F')] # max salary of female student which is in arts.
# a[(a['salary']==a['salary'].max())]
a

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b hsc_s  degree_p   degree_t  \
49      50      F   50.0   Others   37.0   Others  Arts     52.00     Others   
76      77      F   66.5   Others   70.4  Central  Arts     71.93  Comm&Mgmt   
122    123      F   66.5  Central   66.8  Central  Arts     69.30  Comm&Mgmt   
136    137      F   47.0  Central   59.0  Central  Arts     64.00  Comm&Mgmt   
148    149      F   77.0  Central   86.0  Central  Arts     56.00     Others   
193    194      F   60.0  Central   63.0  Central  Arts     56.00     Others   

    workex  etest_p specialisation  mba_p      status    salary  
49      No     65.0         Mkt&HR  56.11  Not Placed       NaN  
76      No     61.0        Mkt&Fin  64.27      Placed  230000.0  
122    Yes     80.4        Mkt&Fin  71.00      Placed  236000.0  
136     No     78.0        Mkt&Fin  61.58  Not Placed       NaN  
148     No     57.0        Mkt&Fin  64.08      Placed  240000.0  
193    Yes     80.0         Mkt&HR  56.63      Placed  300000.0

In [45]:
#8.7
a=pla.loc[(pla['hsc_s']=='Commerce')&(pla['gender']=='M'),'salary']
a
pla[pla['salary']==a.min()]# same problem

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
1        2      M  79.33  Central  78.33   Others   Science     77.48   
15      16      F  65.00  Central  75.00  Central  Commerce     69.00   
44      45      F  77.00   Others  73.00   Others  Commerce     81.00   
50      51      F  75.20  Central  73.20  Central   Science     68.40   
107    108      M  82.00   Others  90.00   Others  Commerce     83.00   
135    136      F  72.00  Central  56.00   Others   Science     69.00   

      degree_t workex  etest_p specialisation  mba_p  status    salary  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28  Placed  200000.0  
15   Comm&Mgmt    Yes     72.0        Mkt&Fin  64.66  Placed  200000.0  
44   Comm&Mgmt    Yes     89.0        Mkt&Fin  69.70  Placed  200000.0  
50   Comm&Mgmt     No     65.0         Mkt&HR  62.98  Placed  200000.0  
107  Comm&Mgmt     No     80.0         Mkt&HR  73.52  Placed  200000.0  
135  Comm&Mgmt     No     55.6         Mkt&HR  65.63  Placed  200000.0

In [62]:
#8.8
s=pla.loc[(pla['hsc_s']=='Commerce')&(pla['degree_t']=='Sci&Tec'),'salary']
pla[pla['salary']==s.min()]

Empty DataFrame
Columns: [sl_no, gender, ssc_p, ssc_b, hsc_p, hsc_b, hsc_s, degree_p, degree_t, workex, etest_p, specialisation, mba_p, status, salary]
Index: []

In [64]:
#8.9
c=pla.loc[(pla['hsc_s']=='Commerce')&(pla['degree_t']=='Sci&Tec')&(pla['workex']=='No'),'salary']
pla[pla['salary']==c.max()]

Empty DataFrame
Columns: [sl_no, gender, ssc_p, ssc_b, hsc_p, hsc_b, hsc_s, degree_p, degree_t, workex, etest_p, specialisation, mba_p, status, salary]
Index: []

In [69]:
#8.10
s=pla[(pla['hsc_s']=='Science')&(pla['degree_t']=='Comm&Mgmt')&(pla['workex']=='Yes')]
s[(s['salary']==s['salary'].min())]

sl_no gender  ssc_p    ssc_b  hsc_p   hsc_b    hsc_s  degree_p  \
154    155      M   53.0  Central   63.0  Others  Science      60.0   

      degree_t workex  etest_p specialisation  mba_p  status    salary  
154  Comm&Mgmt    Yes     70.0        Mkt&Fin   53.2  Placed  250000.0

In [71]:
#8.11
w=pla.loc[(pla['gender']=='F')&(pla['degree_t']=='Mkt&HR')&(pla['workex']=='Yes'),'salary']
pla[pla['salary']==w.min()]

Empty DataFrame
Columns: [sl_no, gender, ssc_p, ssc_b, hsc_p, hsc_b, hsc_s, degree_p, degree_t, workex, etest_p, specialisation, mba_p, status, salary]
Index: []

In [76]:
#8.12
w=pla[(pla['workex']=='No')]
w[(w['salary']==w['salary'].max())]

sl_no gender  ssc_p   ssc_b  hsc_p   hsc_b    hsc_s  degree_p  degree_t  \
163    164      M   63.0  Others   67.0  Others  Science      64.0  Sci&Tech   

    workex  etest_p specialisation  mba_p  status    salary  
163     No     75.0        Mkt&Fin  66.46  Placed  500000.0

In [79]:
#8.13
w=pla[(pla['workex']=='Yes')]
w[(w['salary']==w['salary'].max())]

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
119    120      M   60.8  Central   68.4  Central  Commerce      64.6   

      degree_t workex  etest_p specialisation  mba_p  status    salary  
119  Comm&Mgmt    Yes    82.66        Mkt&Fin  64.34  Placed  940000.0

In [81]:
#8.14
n=pla[(pla['workex']=='No')&(pla['degree_t']=='Sci&Tech')]
n[(n['salary']==n['salary'].min())]

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b    hsc_s  degree_p  \
62      63      F   86.5   Others   64.2   Others  Science      67.4   
117    118      M   77.0   Others   75.0   Others  Science      73.0   
152    153      F   75.4   Others   60.5  Central  Science      84.0   
202    203      M   70.0  Central   63.0  Central  Science      66.0   

     degree_t workex  etest_p specialisation  mba_p  status    salary  
62   Sci&Tech     No    59.00        Mkt&Fin  59.69  Placed  240000.0  
117  Sci&Tech     No    80.00        Mkt&Fin  67.05  Placed  240000.0  
152  Sci&Tech     No    98.00        Mkt&Fin  65.25  Placed  240000.0  
202  Sci&Tech     No    61.28         Mkt&HR  60.11  Placed  240000.0

In [84]:
#8.15
x=pla[(pla['workex']=='No')&(pla['ssc_p']>66)]
x[(x['salary']==x['salary'].max())]

sl_no gender  ssc_p   ssc_b  hsc_p   hsc_b    hsc_s  degree_p  degree_t  \
53     54      M   80.0  Others   70.0  Others  Science      72.0  Sci&Tech   

   workex  etest_p specialisation  mba_p  status    salary  
53     No     87.0         Mkt&HR  71.04  Placed  450000.0

In [85]:
#8.16......8.23
#Confusion in question and solution as well

# 9

In [88]:
arr=np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [98]:
#9.1
arr=arr.reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [99]:
#9.2
#a
print(arr[4:7,6:9])

[[47 48 49]
 [57 58 59]
 [67 68 69]]


In [118]:
#b
print([arr[3:5,9:],[arr[4:7,0:3]]])#Didn't find the solution

[array([[40],
       [50]]), [array([[41, 42, 43],
       [51, 52, 53],
       [61, 62, 63]])]]


In [121]:
#c
arr[3:8,1:9]

array([[32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [52, 53, 54, 55, 56, 57, 58, 59],
       [62, 63, 64, 65, 66, 67, 68, 69],
       [72, 73, 74, 75, 76, 77, 78, 79]])

In [123]:
#d
print([arr[1:4,9:],[arr[2:6,0:9]]])#Didn't find the perfect 

[array([[20],
       [30],
       [40]]), [array([[21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59]])]]
